### ISSUE TITLE
Overrides don't inheret global deaults

### ISSUE THREAD

**Issue by bim9262** [bim9262/calibright#3]
```toml
[global]
ddcci_sleep_multiplier = 0.1
root_scaling = 1.2

[ddcci6]
calibration = [20, 80]

[ddcci7]
calibration = [20, 80]
root_scaling = 1.4
```

should be equivalent to  as:

```toml
[global]
ddcci_sleep_multiplier = 0.1
root_scaling = 1.2

[ddcci6]
ddcci_sleep_multiplier = 0.1
root_scaling = 1.2
calibration = [20, 80]

[ddcci7]
calibration = [20, 80]
ddcci_sleep_multiplier = 0.1
root_scaling = 1.4
```
